// src/app/contact.tsx
import { useActionState } from "react"
import { submitContact } from "~/app/actions"
import { Card } from "~/components/card"

const inputClassName =
  "relative w-full rounded-sm border border-gray-700 bg-gray-800/50 px-2 py-2 font-mono shadow-2xl transition-colors hover:border-gray-600 md:px-5 md:py-3 placeholder:text-gray-400"

export function Contact() {
  const [state, action, isLoading] = useActionState(submitContact, undefined)

  return (
    <Card
      item={{
        title: "Contact us",
        tags: ["Contact"],
        description: null,
        image: null,
        slug: null,
        id: "contact",
        meta: "contact",
        isLikeable: false,
        externalLink: null,
      }}
    >
      <form action={action}>
        {state?.success ? (
          <div className="space-y-2 py-9 text-center">
            <p className="text-2xl">Thank you for your message!</p>
            <p className="text-lg">We will get back to you as soon as possible.</p>
          </div>
        ) : (
          <div className="space-y-2">
            <label htmlFor="name" className="block">
              <span className="w-32">Name</span>
              <input id="name" name="name" required minLength={2} className={inputClassName} />
              {state?.fieldErrors?.name?.map((error) => (
                <p key={error} className="text-red-500 text-sm">
                  {error}
                </p>
              ))}
            </label>
            <label htmlFor="email" className="block">
              <span className="w-32">Email</span>
              <input id="email" required name="email" type="email" className={inputClassName} />
              {state?.fieldErrors?.email?.map((error) => (
                <p key={error} className="text-red-500 text-sm">
                  {error}
                </p>
              ))}
            </label>
            <label htmlFor="message" className="block">
              <span className="w-32">
                Message <span className="text-xs opacity-50">(Min 50 chars)</span>
              </span>
              <textarea rows={5} required id="message" name="message" minLength={50} className={inputClassName} />
              {state?.fieldErrors?.message?.map((error) => (
                <p key={error} className="-mt-1.5 text-red-500 text-sm">
                  {error}
                </p>
              ))}
            </label>
            <div className="opacity-0 h-0">
              <label htmlFor="phone">Phone Number (Required)</label>
              <input id="phone" name="phone" />
            </div>
            <button
              type="submit"
              disabled={isLoading}
              className="rounded-sm bg-gray-700 px-3 py-2 transition-colors hover:bg-gray-600 md:px-8 md:py-3"
            >
              {isLoading ? "Sending..." : "Send it"}
            </button>
          </div>
        )}
      </form>
    </Card>
  )
}

// src/components/Contact.svelte
<script lang="ts">
  import Card from "./Card.svelte"
  let isSubmitted = false
  let isLoading = false

  const handleSubmit = (e: any) => {
    isLoading = true
    const formData = new FormData(e.target)
    const data = Object.fromEntries(formData.entries())
    fetch("/api/contact", {
      method: "POST",
      body: JSON.stringify(data),
    })
      .then(() => {
        e.target.reset()
        isSubmitted = true
      })
      .catch((err) => console.error(err))
      .finally(() => {
        isLoading = false
      })
  }
</script>

<Card title="Contact us" isLikeable={false} link={undefined} description={undefined} tags={[]} images={[]}>
  <form action="/api/contact" method="post" on:submit={handleSubmit}>
    {#if isSubmitted}
      <div class="text-center py-9 space-y-2">
        <p class="text-2xl">Thank you for your message!</p>
        <p class="text-lg">We will get back to you as soon as possible.</p>
      </div>
    {:else}
      <div class="space-y-2">
        <label for="name" class="block w-full">
          <span class="w-32">Name</span>
          <input
            id="name"
            name="name"
            required
            minlength="2"
            class="relative w-full rounded-lg border border-neutral-700 bg-neutral-800/50 px-2 py-2 md:py-3 md:px-8 font-mono shadow-2xl transition-colors placeholder:text-neutral-400 hover:border-neutral-600"
          />
        </label>
        <label for="email" class="block w-full">
          <span class="w-32">Email</span>
          <input
            id="email"
            required
            name="email"
            type="email"
            class="relative w-full rounded-lg border border-neutral-700 bg-neutral-800/50 px-2 py-2 md:py-3 md:px-8 font-mono shadow-2xl transition-colors placeholder:text-neutral-400 hover:border-neutral-600"
          />
        </label>
        <label for="message" class="block w-full">
          <span class="w-32">Message</span>
          <textarea
            rows="5"
            required
            id="message"
            name="message"
            minlength="100"
            class="resize-none relative w-full rounded-lg border border-neutral-700 bg-neutral-800/50 px-2 py-2 md:py-3 md:px-8 font-mono shadow-2xl transition-colors placeholder:text-neutral-400 hover:border-neutral-600"
          />
        </label>
        <button
          type="submit"
          disabled={isLoading}
          class="rounded-lg bg-neutral-700 px-3 py-2 md:py-3 md:px-8 transition-colors hover:bg-neutral-600"
        >
          {#if isLoading}
            Sending...
          {:else}
            Send it
          {/if}
        </button>
      </div>
    {/if}
  </form>
</Card>
